1st pass of cleanup and a bit of hardening. 4 bugs discovered and added in README.

diff --git a/todo b/todo
--- a/todo
+++ b/todo
@@ -37,21 +37,21 @@ usage() {
     echo "Usage: ${0} [option] [argument]
 
     -a : List All tasks.
-    -b \"filename\" : Binary backup of database to filename (which must not exist).
+    -b \"filename\" : Binary Backup of database to filename (which must not exist).
     -c rowid : Mark task with rowid as Completed at the moment the command is issued.
     -d rowid : Delete task with rowid from database (no cancel possible).
-    -h : This help.
-    -i : informations about database.
-    -m \"/absolute/path\": move database to another directory and update .todorc file accordingly.
-    -M \"/absolute/path\" : move database to another directory, update .todorc file accordingly, and create dir if it does not exist.
+    -h : This Help.
+    -i : Informations about database.
+    -m \"/absolute/path\": Move database to another directory and update .todorc file accordingly.
+    -M \"/absolute/path\" : Move database to another directory, update .todorc file accordingly, and create dir if it does not exist.
     -n \"task description\" : Create a New task. Creation time is stored at the moment command is issued.
     -p \"filename\" : DumP database in SQL format to a given file. Content will be overwritten if existing.
     -r \"filename\" : Restore a binary backup. !!! BEWARE !!! Database will be overwritten (previous content will be lost).
     -s word : Search for not yet completed tasks containing \" word \" (case insensitive search).
     -S word : Search for still valid and completed tasks containing \" word \" (case insensitive search).
     -t \"filename\" : ImporT a dump file in SQL format. !!! BEWARE !!! Database content will be erased before import.
-    -u rowid : Mark as Unfinished a task previously marked as completed.
-    -v : Version.
+    -u rowid : Mark as Unfinished a task previously marked as Completed.
+    -v : Display Version.
 
 Your todo database path is stored in ~/.todorc, which defaults to ~/.todo.db
 
@@ -67,22 +67,22 @@ error () {
     else
         echo "Something bad happened."
     fi
-    exit 3
 }
 
 informations () {
-    query="SELECT * FROM info;"
+    local readonly query="SELECT * FROM info;"
     echo "Your todo database is located at: \"${1}\"
 SQL mode used, database creation time, todo version when db was created, SQLite version at db creation."
     "${sqlite3}" -header -column "${TODODB}" "${query}" || { error "informations function: ${query}" ; exit 3 ; }
+    echo
     "${sqlite3}" "${TODODB}" ".dbinfo" || { error "informations function: .dbinfo" ; exit 3 ; }
 }
 
 initializedb () {
-    now=$(date +"%Y-%m-%d %R:%S")
-    sqliteversion="$(${sqlite3} --version)"
-    query="CREATE TABLE info(sqlmode TEXT NOT NULL, creation TEXT NOT NULL, todoversion TEXT NOT NULL, sqliteversion TEXT NOT NULL);"
-    insert="INSERT INTO info(sqlmode, creation, todoversion, sqliteversion) VALUES ('${ACTUALSQLMODE}', '${now}', '${version}', '${sqliteversion}');"
+    local readonly now=$(date +"%Y-%m-%d %R:%S")
+    local readonly sqliteversion="$(${sqlite3} --version)"
+    local readonly query="CREATE TABLE info(sqlmode TEXT NOT NULL, creation TEXT NOT NULL, todoversion TEXT NOT NULL, sqliteversion TEXT NOT NULL);"
+    local readonly insert="INSERT INTO info(sqlmode, creation, todoversion, sqliteversion) VALUES ('${ACTUALSQLMODE}', '${now}', '${version}', '${sqliteversion}');"
     case "${ACTUALSQLMODE}" in
         "db"   ) query2="CREATE TABLE todo (title TEXT NOT NULL, creation TEXT NOT NULL, completed TEXT);" ;;
         "fts3" ) query2="CREATE VIRTUAL TABLE todo USING ${ACTUALSQLMODE}(title TEXT NOT NULL, creation TEXT NOT NULL, completed TEXT);" ;;
@@ -103,9 +103,10 @@ initializedb () {
 }
 
 addentry () {
-    now=$(date +"%Y-%m-%d %R:%S")
-    query="INSERT INTO todo(title, creation, completed) VALUES('${1}', '${now}', NULL);"
+    local readonly now=$(date +"%Y-%m-%d %R:%S")
+    local readonly query="INSERT INTO todo(title, creation, completed) VALUES('${1}', '${now}', NULL);"
     "${sqlite3}" "${TODODB}" "${query}" || { error "addentry function: ${query}" ; exit 3 ; }
+    echo "Task successfully added. Be brave !"
 }
 
 completeentry () {
@@ -113,16 +114,18 @@ completeentry () {
     then
         usage
     else
-        declare -i id
-        id="${1}"
+        declare -i -r id="${1}"
         if [ "${id}" != "${1}" ]
         then
             #id is not numeric
             usage
         else
-            now=$(date +"%Y-%m-%d %R:%S")
-            query="UPDATE todo SET completed='${now}' WHERE rowid=${id};"
+            local readonly now=$(date +"%Y-%m-%d %R:%S")
+            local readonly query="UPDATE todo SET completed='${now}' WHERE rowid=${id};"
+            # TODO check if task is already marked as completed or simply update completed field ?
+            # local readonly alreadycompleted="SELECT rowid FROM todo "
             "${sqlite3}" "${TODODB}" "${query}" || { error "completeentry function: ${query}" ; exit 3 ; }
+            echo "Task ${id} marked as completed. Keep up the good work ! :)"
         fi
     fi
 }
@@ -132,14 +135,14 @@ unfinishentry () {
     then
         usage
     else
-        declare -i id
-        id="${1}"
+        declare -i -r id="${1}"
         if [ "${id}" != "${1}" ]
         then
             #id is not numeric
             usage
         else
-            query="UPDATE todo SET completed=NULL WHERE rowid=${id};"
+            # TODO check if task is already marked as unfinished or simply update field ?
+            local readonly query="UPDATE todo SET completed=NULL WHERE rowid=${id};"
             "${sqlite3}" "${TODODB}" "${query}" || { error "unfinishentry function: ${query}" ; exit 3 ; }
         fi
     fi
@@ -151,25 +154,25 @@ deleteentry () {
         usage
     else
         declare -i id
-        id="${1}"
+        local id="${1}"
         if [ "${id}" != "${1}" ]
         then
             #id is not numeric
             usage
         else
-            query="DELETE FROM todo WHERE rowid=${id};"
+            local readonly query="DELETE FROM todo WHERE rowid=${id};"
             "${sqlite3}" "${TODODB}" "${query}" || { error "deleteentry function: ${query}" ; exit 3 ; }
         fi
     fi
 }
 
 listentries () {
-    query="SELECT rowid, title, creation FROM todo WHERE completed IS NULL;"
+    local readonly query="SELECT rowid, title, creation FROM todo WHERE completed IS NULL;"
     "${sqlite3}" ${SQLITEOPTS} "${TODODB}" "${query}" 2> /dev/null  || { error "listentries function: ${query}" ; exit 3 ; }
 }
 
 listallentries () {
-    query="SELECT rowid, title, creation, completed FROM todo;"
+    local readonly query="SELECT rowid, title, creation, completed FROM todo;"
     "${sqlite3}" ${SQLITEOPTS} "${TODODB}" "${query}" 2> /dev/null || { error "listallentries function: ${query}" ; exit 3 ; }
 }
 
@@ -177,8 +180,8 @@ search () {
     if [ ! -z "${1}" ]
     then
         case "${SQLMODE}" in
-            "db"   ) query="SELECT rowid, title, creation FROM todo WHERE completed IS NULL AND title LIKE '%${1}%';" ;;
-            "fts3" ) query="SELECT rowid, title, creation FROM todo WHERE completed IS NULL AND title MATCH '${1}';" ;;
+            "db"   ) local readonly query="SELECT rowid, title, creation FROM todo WHERE completed IS NULL AND title LIKE '%${1}%';" ;;
+            "fts3" ) local readonly query="SELECT rowid, title, creation FROM todo WHERE completed IS NULL AND title MATCH '${1}';" ;;
             *      ) echo "${SQLMODE}" "is not a valid SQLMODE value. That definitively should not have happened. Please report a bug at ${repo}"; exit 2 ;;
         esac
     else
@@ -191,8 +194,8 @@ searchall () {
     if [ ! -z "${1}" ]
     then
         case "${SQLMODE}" in
-            "db"   ) query="SELECT rowid, title, creation, completed FROM todo WHERE title LIKE '%${1}%';" ;;
-            "fts3" ) query="SELECT rowid, title, creation, completed FROM todo WHERE title MATCH '${1}';" ;;
+            "db"   ) local readonly query="SELECT rowid, title, creation, completed FROM todo WHERE title LIKE '%${1}%';" ;;
+            "fts3" ) local readonly query="SELECT rowid, title, creation, completed FROM todo WHERE title MATCH '${1}';" ;;
             *      ) echo "${SQLMODE}" "is not a valid SQLMODE value. That definitively should not have happened. Please report a bug at ${repo}"; exit 2 ;;
         esac
     else
@@ -269,9 +272,12 @@ dump () {
 import () {
     if [ ! -z "${1}" ] && [ -r "${1}" ] && [ -f "${1}" ]
     then
+        # TODO do a backup before importing.
         "${sqlite3}" "${TODODB}" "DROP TABLE info;" || { error "import function. DROP TABLE info;" ; exit 3 ; }
+        echo "info table has been successfully dropped."
         "${sqlite3}" "${TODODB}" "DROP TABLE todo;" || { error "import function. DROP TABLE info;" ; exit 3 ; }
-        "${sqlite3}" "${TODODB}" < "${1}"  || { error "import function at import phase." ; exit 3 ; }
+        echo "todo table has been successfully dropped."
+        "${sqlite3}" "${TODODB}" ".import '${1}'"  || { error "import function at import phase." ; exit 3 ; }
         echo "todo database dump \"${1}\" has successfully replaced \"${TODODB}\" content."
     else
         error "\"${1}\" is either empty, non readable, or not a file. Database was not modified."
@@ -282,7 +288,7 @@ backup () {
     # do a binary backup of database.
     if [ ! -z "${1}" ] && [ ! -e "${1}" ]
     then
-        "${sqlite3}" "${TODODB}" ".backup ${1}" || { error "backup function : Error while backup-ing database to \"${1}\". Exiting." ; exit 7 ; }
+        "${sqlite3}" "${TODODB}" ".backup '${1}'" || { error "backup function : Error while backup-ing database to \"${1}\". Exiting." ; exit 7 ; }
         echo "\"${TODODB}\" was successfully backup-ed to \"${1}\""
     else
         echo "\"${1}\" is either empty or already existing. Backup aborded."
@@ -294,13 +300,14 @@ restore () {
     if [ ! -z "${1}" ] && [ -f "${1}" ] && [ -r "${1}" ]
     then
         # be sure the file to restore is a SQLite database.
-        type=$(file "${1}" | grep "SQLite 3" | wc -l)
+        local readonly type=$(file "${1}" | grep "SQLite 3" | wc -l)
+        # 0 means this is not a SQLite3 file, 0 being « true » in shell.
         if [ ! ${type} ]
         then
             echo "\"${1}\" is not a SQLite 3 database. Cannot restore. Exiting."
             exit 7
         else
-            "${sqlite3}" "${TODODB}" ".restore ${1}" || { error "restore function : Error while restoring database. Disk full ? Database may be corrupted :(. Exiting." ; exit 7 ; }
+            "${sqlite3}" "${TODODB}" ".restore '${1}'" || { error "restore function : Error while restoring database. Disk full ? Database may be corrupted :(. Exiting." ; exit 7 ; }
             echo "Database successfully restored from backup \"${1}\""
         fi
     else
@@ -319,7 +326,7 @@ sqlite3checks () {
     fi
     # test if FTS is available
     ACTUALSQLMODE="fts3"
-    tmp="$(mktemp)"
+    local readonly tmp="$(mktemp)"
     "${sqlite3}" "${tmp}" "CREATE VIRTUAL TABLE test USING ${ACTUALSQLMODE}(title TEXT NOT NULL);" 2> /dev/null || ACTUALSQLMODE="db"
     # prevent remaining tmp file if todo is interrupted
     trap "rm -f '${tmp}' ; exit " INT TERM EXIT
@@ -343,90 +350,91 @@ dbchecks () {
 }
 
 movedb () {
-	if [ ! -d "${1}" ]
-	then
-		echo "\"${1}\" is not a directory"
-		exit 5
-	else
-		# we can write, there’s no ${1}/.todo.db, and directory begins with a / (absolute path)
-		if [ -w "${1}" ] && [ ! -e "${1}/.todo.db" ] && [ "${1:0:1}" == "/" ]
-		then
-			mv "${TODODB}" "${1}/" || { error "Move of database has failed. ~/.todorc has not been modified." ; exit 8 ; }
-			echo "TODODB=\"${1}/.todo.db\"" > "${TODORC}.new"
-			echo "SQLITEOPTS=\"${SQLITEOPTS}\"" >> "${TODORC}.new"
-			mv -f "${TODORC}.new" "${TODORC}"
-		else
-			echo "Either \"${1}\" is not writable, or \"${1}/.todo.db\" already exists. Please fix."
-			exit 8
-		fi
-	fi
+    if [ ! -d "${1}" ]
+    then
+        echo "\"${1}\" is not a directory"
+        exit 5
+    else
+        # we can write, there’s no ${1}/.todo.db, and directory begins with a / (absolute path)
+        if [ -w "${1}" ] && [ ! -e "${1}/.todo.db" ] && [ "${1:0:1}" == "/" ]
+        then
+            mv "${TODODB}" "${1}/" || { error "Move of database has failed. ~/.todorc has not been modified." ; exit 8 ; }
+            echo "TODODB=\"${1}/.todo.db\"" > "${TODORC}.new"
+            echo "SQLITEOPTS=\"${SQLITEOPTS}\"" >> "${TODORC}.new"
+            mv -f "${TODORC}.new" "${TODORC}"
+        else
+            echo "Either \"${1}\" is not writable, or \"${1}/.todo.db\" already exists. Please fix."
+            exit 8
+        fi
+    fi
 }
 
 mkdirmovedb () {
-	if [ ! -d "${1}" ] && [ "${1:0:1}" == "/" ]
-	then
-		mkdir -p "${1}" || error "Error creating new directory to store database."
-		exit 5
-	else
-		if [ "${1:0:1}" == "/" ]
-		then
-			echo "\"${1}\" is not an absolute path."
-			exit 5
-		fi
-	fi
-	# we can write, and there’s no ${1}/.todo.db
-	if [ -w "${1}" ] && [ ! -e "${1}/.todo.db" ]
-	then
-		mv "${TODODB}" "${1}/" || { error "Move of database has failed. ~/.todorc has not been modified." ; exit 8 ; }
-		echo "TODODB=\"${1}/.todo.db\"" > "${TODORC}.new"
-		echo "SQLITEOPTS=\"${SQLITEOPTS}\"" >> "${TODORC}.new"
-		mv -f "${TODORC}.new" "${TODORC}"
-	else
-		echo "Either \"${1}\" is not writable, or \"${1}/.todo.db\" already exists. Please fix."
-		exit 8
-	fi
+    if [ ! -d "${1}" ] && [ "${1:0:1}" == "/" ]
+    then
+        mkdir -p "${1}" || error "Error creating new directory to store database."
+        exit 5
+    else
+        if [ "${1:0:1}" == "/" ]
+        then
+            echo "\"${1}\" is not an absolute path."
+            exit 5
+        fi
+    fi
+    # we can write, and there’s no ${1}/.todo.db
+    if [ -w "${1}" ] && [ ! -e "${1}/.todo.db" ]
+    then
+        mv "${TODODB}" "${1}/" || { error "Move of database has failed. ~/.todorc has not been modified." ; exit 8 ; }
+        echo "TODODB=\"${1}/.todo.db\"" > "${TODORC}.new"
+        echo "SQLITEOPTS=\"${SQLITEOPTS}\"" >> "${TODORC}.new"
+        mv -f "${TODORC}.new" "${TODORC}"
+    else
+        echo "Either \"${1}\" is not writable, or \"${1}/.todo.db\" already exists. Please fix."
+        exit 8
+    fi
 }
 
 main () {
-	#satisfy set -u
-	args=${1:-}
-	if [ -z "${args}" ]
-	then
-		listentries
-	else
-		if ( ! getopts ab:c:d:him:M:n:p:r:s:S:t:u:v OPT )
-		then
-			usage
-			exit 1
-		fi
-	fi
+    #satisfy set -u
+    local readonly args=${1:-}
+    if [ -z "${args}" ]
+    then
+        listentries
+        exit
+    else
+        if ( ! getopts ab:c:d:him:M:n:p:r:s:S:t:u:v OPT )
+        then
+            usage
+            exit 1
+        fi
+    fi
 
-	while getopts ab:c:d:him:M:n:p:r:s:S:t:u:v OPT;
-	do
-		case $OPT in
-			a) listallentries ;;
-			b) backup "$OPTARG" ;;
-			c) completeentry "$OPTARG" ;;
-			d) deleteentry "$OPTARG" ;;
-			h) usage ;;
-			i) informations "${TODODB}" ;;
-			m) movedb "$OPTARG" ;;
-			M) mkdirmovedb "$OPTARG" ;;
-			n) addentry "$OPTARG" ;;
-			p) dump "$OPTARG" ;;
-			r) restore "$OPTARG" ;;
-			s) search "$OPTARG" ;;
-			S) searchall "$OPTARG" ;;
-			t) import "$OPTARG" ;;
-			u) unfinishentry "$OPTARG" ;;
-			v) version ;;
-			\?) usage
-				exit ;;
-			:) echo "Missing argument for $OPT"
-				usage
-				exit ;;
-		esac
-	done
+    while getopts ab:c:d:him:M:n:p:r:s:S:t:u:v OPT;
+    do
+        case $OPT in
+            a) listallentries ;;
+            b) backup "$OPTARG" ;;
+            c) completeentry "$OPTARG" ;;
+            d) deleteentry "$OPTARG" ;;
+            h) usage ;;
+            i) informations "${TODODB}" ;;
+            m) movedb "$OPTARG" ;;
+            M) mkdirmovedb "$OPTARG" ;;
+            n) addentry "$OPTARG" ;;
+            p) dump "$OPTARG" ;;
+            r) restore "$OPTARG" ;;
+            s) search "$OPTARG" ;;
+            S) searchall "$OPTARG" ;;
+            t) import "$OPTARG" ;;
+            u) unfinishentry "$OPTARG" ;;
+            v) version ;;
+            \?) usage
+                exit ;;
+            :) echo "Missing argument for $OPT"
+                usage
+                exit ;;
+        esac
+    done
 }
 
 todosqliterc
